### ISSUE TITLE
Allow json key policies as input

### ISSUE THREAD

**Issue by dudicoco** [terraform-aws-modules/terraform-aws-kms#17]
## Is your request related to a problem? Please describe.

Currently the `key_statements` input variable enforces a specific syntax on the user:
https://github.com/terraform-aws-modules/terraform-aws-kms/blob/87be9ccb61f073b58ed56de0456214c34d793841/main.tf#L389-L429

This prevents the user from using standard json documents for the policy and also adds redundant code to the module as this basically duplicates the `aws_iam_policy_document` syntax.

## Describe the solution you'd like.

Allow the user to specify a policy json, see examples:

```hcl
policy = jsonencode({
  "Version" : "2012-10-17",
  "Statement" : {
    "Effect" : "Allow",
    "Principal" : {
      "AWS" : "arn:aws:iam::112233445566:root"
    },
    "Action" : "kms:*",
    "Resource" : "*"
  } 
})
```

```hcl
policy = aws_iam_policy_document.example.json
```

**Comment by bryantbiggs** [comment]
you can use `source_policy_documents` for this

**Comment by dudicoco** [comment]
Thanks @bryantbiggs, I must have missed it.
