### ISSUE TITLE
enable_key_rotation should be automatically set to false for SIGN_VERIFY keys

### ISSUE THREAD

**Issue by gilbahat** [terraform-aws-modules/terraform-aws-kms#20]
## Description

key rotation is invalid for keys of type SIGN_VERIFY. when enable_key_rotation is not actively set to false for such a key, the provider will throw an error:

│ Error: creating KMS Key (redacted):  key rotation: UnsupportedOperationException:
│
│   with module.kms.aws_kms_key.this[0],
│   on .terraform/modules/kms/main.tf line 8, in resource "aws_kms_key" "this":
│    8: resource "aws_kms_key" "this" {

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:
1.5.0

- Terraform version:

✗ terraform -version                                                                                                      <aws:Distribution.AdministratorAccess>
Terraform v1.5.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.67.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/olivr/gpg v0.2.1

## Reproduction Code [Required]

module "kms" {
  source = "terraform-aws-modules/kms/aws"

  description = "Cosign signing key"
  key_usage   = "SIGN_VERIFY"
  customer_master_key_spec = "RSA_4096"

  # Aliases
  aliases = ["alias/redacted"]

}

terraform apply

## Expected behavior

KMS key created

## Actual behavior

│ Error: creating KMS Key (redacted):  key rotation: UnsupportedOperationException:
│
│   with module.kms.aws_kms_key.this[0],
│   on .terraform/modules/kms/main.tf line 8, in resource "aws_kms_key" "this":
│    8: resource "aws_kms_key" "this" {

## Additional context

from https://docs.aws.amazon.com/kms/latest/developerguide/rotate-keys.html :
"The Key rotation tab appears only on the detail page of *symmetric encryption KMS keys* with key material that AWS KMS generated (the Origin is AWS_KMS), including multi-Region symmetric encryption KMS keys."

**Comment by bryantbiggs** [comment]
I'm not quite following - this `UnsupportedOperationException` means the API is stating its not a supported operation, which is outside the scope of the module

**Comment by gilbahat** [comment]
> I'm not quite following - this `UnsupportedOperationException` means the API is stating its not a supported operation, which is outside the scope of the module

this happens because of poor default value for enable_key_rotation in the module: it defaults to true regardless of whether key rotation is supported or not.

I would expect the module to do two things:

1. set the default according to the value of key_usage: true if ENCRYPT_DECRYPT but false if SIGN_VERIFY
2. throw a clear and meaningful error message if the user attempts to set SIGN_VERIFY and enable_key_rotation - "asymmetric keys do not support rotation"

**Comment by bryantbiggs** [comment]
> throw a clear and meaningful error message

Terraform does not support this. The module is designed with a set of default values and assumptions, but deviating from the defaults will require users to set the values correctly per the underlying AWS API
