### ISSUE TITLE
Cannot replicate multi-region key due to missing permission

### ISSUE THREAD

**Issue by kstevensonnv** [terraform-aws-modules/terraform-aws-kms#22]
## Description

When creating a multi-region key, the 'key_administrators' IAM policy does not provide the 'kms:ReplicateKey' permission and replication fails with an access denied error.

The [comment](https://github.com/terraform-aws-modules/terraform-aws-kms/blob/master/main.tf#L121) above the IAM policy for 'key_administrators' points to [AWS KMS docs - Default key policy (key administrators)](https://docs.aws.amazon.com/kms/latest/developerguide/key-policy-default.html#key-policy-default-allow-administrators) and states:

> AWS KMS adds the following permissions to the default key administrators statement when you create [special-purpose keys](https://docs.aws.amazon.com/kms/latest/developerguide/key-types.html).
>
>kms:ReplicateKey
&nbsp;&nbsp;&nbsp;&nbsp;The [kms:ReplicateKey](https://docs.aws.amazon.com/kms/latest/APIReference/API_ReplicateKey.html) permission allows key administrators to [create a replica of a multi-Region primary key](https://docs.aws.amazon.com/kms/latest/developerguide/multi-region-keys-replicate.html) in a &nbsp;&nbsp;&nbsp;&nbsp;different AWS Region. This permission is included in the key policy only when you create a multi-Region primary or &nbsp;&nbsp;&nbsp;&nbsp;replica key.
>
>kms:UpdatePrimaryRegion
&nbsp;&nbsp;&nbsp;&nbsp;The [kms:UpdatePrimaryRegion](https://docs.aws.amazon.com/kms/latest/APIReference/API_UpdatePrimaryRegion.html) permission allows key administrators to [change a multi-Region replica key to a &nbsp;&nbsp;&nbsp;&nbsp;multi-Region primary key](https://docs.aws.amazon.com/kms/latest/developerguide/multi-region-keys-manage.html#multi-region-update). This permission is included in the key policy only when you create a multi-Region &nbsp;&nbsp;&nbsp;&nbsp;primary or replica key.

This doesn't happen when creating it via Terraform.
Both permissions should be added to the policy.

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 1.5.0

- Terraform version: 1.5.5
- Provider version(s):
>.
├── provider[registry.terraform.io/hashicorp/helm] ~> 2.10.1
├── provider[registry.terraform.io/hashicorp/kubernetes] ~> 2.23.0
├── provider[registry.terraform.io/hashicorp/random] ~> 3.5.1
├── provider[registry.terraform.io/hashicorp/aws] ~> 5.12.0
├── module.cluster_secrets_kms_primary
│   └── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0
└── module.cluster_secrets_kms_replica
    └── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0

## Reproduction Code [Required]

```
provider "aws" {
  region   = "eu-west-1"
  profile  = "profile"
}

provider "aws" {
  alias    = "replica"
  region   = "eu-west-2"
  profile  = "profile"
}

data "aws_caller_identity" "current" {}

module "kms_primary" {
  source  = "terraform-aws-modules/kms/aws"

  description             = "Primary"
  key_usage               = "ENCRYPT_DECRYPT"
  deletion_window_in_days = 7
  enable_key_rotation     = true

  multi_region = true

  enable_default_policy = false
  key_administrators    = [data.aws_caller_identity.current.arn]
  key_users             = [data.aws_caller_identity.current.arn]
}

module "kms_replica" {
  source  = "terraform-aws-modules/kms/aws"

  providers = {
    aws = aws.replica
  }

  description             = "Replica"
  key_usage               = "ENCRYPT_DECRYPT"
  deletion_window_in_days = 7
  enable_key_rotation     = false

  create_replica  = true
  primary_key_arn = module.kms_primary.key_arn

  enable_default_policy = false
  key_administrators    = [data.aws_caller_identity.current.arn]
  key_users             = [data.aws_caller_identity.current.arn]
}
```

## Expected behavior

The key is replicated in another region.

## Actual behavior

Access denied error:

>Error: creating KMS Replica Key: AccessDeniedException: User: arn:aws:sts::account:assumed-role/role/session_id is not authorized to perform: kms:ReplicateKey on resource: arn:aws:kms:region:account:key/mrk-key because no resource-based policy allows the kms:ReplicateKey action
status code: 400, request id: id

**Comment by antonbabenko** [comment]
This issue has been resolved in version 2.0.1 :tada:
