### ISSUE TITLE
key_pair module reports incorrect latest version

### ISSUE THREAD

**Issue by vstthomas** [terraform-aws-modules/terraform-aws-kms#31]
## Description

The `terraform init` process errors with `The newest available version is 2.0.3`; according to the releases, the latest version is `2.2.1`.

```shell
% make init
terraform init -get=true -backend=true -reconfigure

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
Initializing modules...
╷
│ Error: Unresolvable module version constraint
│ 
│   on key-pair.tf line 9:
│    9: module "key_pair" {
│ 
│ There is no available version of module "registry.terraform.io/terraform-aws-modules/key-pair/aws" (key-pair.tf:9) which matches the given version constraint. The newest available version is 2.0.3.
╵
```

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

```tf
module "key_pair" {
  source  = "terraform-aws-modules/key-pair/aws"
  version = "~> 2.2.1"
...
}
```

- Terraform version:

% tf version
Terraform v1.7.5
on darwin_arm64

- Provider version(s):
+ provider registry.terraform.io/hashicorp/aws v5.47.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.4
+ provider registry.terraform.io/hashicorp/helm v2.13.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.29.0
+ provider registry.terraform.io/hashicorp/null v3.2.2
+ provider registry.terraform.io/hashicorp/time v0.11.1
+ provider registry.terraform.io/hashicorp/tls v4.0.5

## Reproduction Code [Required]

Workspaces: no
Clear Cache: yes

Steps to Reproduce

1. Create module like

```tf
module "key_pair" {
  source  = "terraform-aws-modules/key-pair/aws"
  version = "~> 2.2.1"

  key_name_prefix    = local.name
  create_private_key = true

  tags = local.tags
}
```

2. `terraform init`
3. ERROR

> _The newest available version is 2.0.3._

## Expected behavior

The module initializes.

## Actual behavior

The module failed `init` for the version number.

**Comment by antonbabenko** [comment]
```
module "key_pair" {
  source  = "terraform-aws-modules/key-pair/aws"
  version = "~> 2.2.1"  # 2.0.3 does not satisfy this condition
...
}
```

You should use `version = "~> 2.0"` or similar.

**Comment by vstthomas** [comment]
@bryantbiggs  Good tips, thank you. I did not have `-upgrade` in there; that helped.

@antonbabenko, updated the version to reflect suggested. But, `version = "~> 2.0"` doesn't get me to `2.2.1`. 
In this case, I've upgraded all modules (using the same method) but only the `key_pair` errors; not sure why the others worked without it then 🤔

Any ideas?

**Comment by antonbabenko** [comment]
There is no module `terraform-aws-modules/key-pair/aws` with version 2.2.1 (only 2.0.3 - https://registry.terraform.io/modules/terraform-aws-modules/key-pair/aws/latest )

**Comment by vstthomas** [comment]
The link was miss-documented in the code 😞 it's always the details.
