### ISSUE TITLE
Part of eks module docs came from s3-bucket module

### ISSUE THREAD

**Issue by hamlethakobyan-zema** [terraform-aws-modules/terraform-aws-kms#34]
## Description
In the wrappers part of documentation [here](https://github.com/terraform-aws-modules/terraform-aws-kms/tree/master/wrappers#example-manage-multiple-s3-buckets-in-one-terragrunt-layer) you can see that we have something related to `s3-bucket` module coming from [here](https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/blob/master/wrappers/README.md).

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:
master branch

- Terraform version:
- Provider version(s): doesn't related

## Reproduction Code [Required]

Doesn't related to code

Just have a look :)

## Expected behavior

Need to be eks module documentation

## Actual behavior

eks module doc is from s3-bucket module

**Comment by bryantbiggs** [comment]
it didn't come from there per se - that is the default docs generated by the wrapper hook
